Add integration test for lldb in the toolchain
swiftlang/vscode-swift pull request #1118
Opened 2024-10-02 19:20 UTC by michael-weng

Issue: #1023

2024-10-04 14:12 UTC, award999 requested changes
The test scenarios look good, some minor style comments

2024-10-04 14:55 UTC, michael-weng commented on test/integration-tests/debugger/lldb.test.ts
> +        const workspaceContext = await WorkspaceContext.create(
Done.

2024-10-04 14:59 UTC, michael-weng commented on test/integration-tests/debugger/lldb.test.ts
> +        const toolchain = await SwiftToolchain.create();
Done.

2024-10-07 16:26 UTC, award999 approved these changes

2024-10-09 16:14 UTC, award999 commented
> Issue: #1023

Before we merge can you add more details of what was tested?

2024-10-18 13:33 UTC, award999 requested changes
@michael-weng can you rebase and run "npm test" locally again? BTW great example here of test with explicit setup (acquire toolchain), 1 action (get path), and a good isolated assertion(s)

2024-10-18 19:39 UTC, michael-weng commented
> @michael-weng can you rebase and run "npm test" locally again? BTW great example here of test with explicit setup (acquire toolchain), 1 action (get path), and a good isolated assertion(s)

Done tests passed.

2024-10-18 19:40 UTC, merged