Update title of command to select toolchain (or Xcode directory)
swiftlang/vscode-swift pull request #924
Opened 2024-06-21 00:55 UTC by aoberoi

Just fixing an outdated part of the README that probably should have landed with #817.

I am not sure if the Select Toolchain command is only available under macOS. That might be an outdated concept since the previous command was about selecting Xcode versions, which obviously are only on macOS. Toolchains are available on other platforms. I'm happy to update this PR if someone wants to confirm this one way or another.

2024-06-21 10:55 UTC, award999 requested changes
Thanks for the PR 👍 but this is not just a macOS concept anymore. @matthewbastien can you advise on this one?

2024-06-28 23:07 UTC, aoberoi commented
Request change integrated. Ready for re-review/merge 😄

2024-06-29 11:43 UTC, adam-fowler approved these changes

2024-07-02 12:45 UTC, award999 approved these changes

2024-07-02 13:27 UTC, 0xTim approved these changes

2024-07-03 13:47 UTC, matthewbastien approved these changes

2024-07-03 13:47 UTC, merged