Update and refine settings descriptions
swiftlang/vscode-swift pull request #957
Opened 2024-07-08 18:19 UTC by plemarquand

- Remove redundant settings descriptions from settings.md, moving any extra information found there in to the setting description shown in the extension settings page.
- Add information on how to enable experimental sourcekit-lsp features to settings.md.
- Consistently apply markdown formatting to setting descriptions.

Fixes #956

2024-07-08 18:24 UTC, plemarquand commented
@adam-fowler Instead of maintaining two largely identical settings descriptions I just rolled everything in to the settings descriptions in the package.json. I think this should be the single source of truth as most users won't seek out the settings.md page, and the'll see these settings descriptions right in the app. If we really want to do a deep dive into a specific setting, so much so that its too much information to have in the extension settings page, we can link out to the settings.md document and expand on it there, but there aren't any that are that long today.

settings.md does now contain some settings combinations/configurations that can be used to accomplish specific things. For instance right now it has sourcekit-lsp server arguments you can set to enable background indexing or peek macro.

2024-07-11 07:23 UTC, adam-fowler requested changes
Combining the two does make it easier to keep everything up to date
I have a few requests for changes.

2024-07-11 07:23 UTC, adam-fowler commented on package.json
> +            "markdownDescription": "Controls how diagnostics from the various providers are merged into the `swift` diagnostics collection.",
Should probably make it clear this is related to diagnostics used in the problems pane. The word diagnostic is not used in the UI anywhere

2024-07-11 07:23 UTC, adam-fowler commented on package.json
> +            "markdownDescription": "Controls which `-diagnostic-style` option to pass to `swiftc` when running `swift` tasks.",
Indicate what effect this has?

2024-07-11 07:23 UTC, adam-fowler commented on package.json
> +            "markdownDescription": "Controls whether or not the extension will contribute Swift environment variables to the integrated terminal.",
Indicate which settings might add environment variables

2024-07-11 07:23 UTC, adam-fowler commented on package.json
> +            "markdownDescription": "Use lldb debug adapter packaged with Swift toolchain as your debug adapter. This is currently only available on Windows platforms or macOS Swift 6",
We can remove the `macOS` from here as the DAP is available on Linux as well

2024-07-11 14:27 UTC, plemarquand commented
@swift-server-bot test this please

2024-07-11 14:57 UTC, adam-fowler commented on package.json
> +            "markdownDescription": "Use lldb debug adapter packaged with Swift toolchain as your debug adapter. This is currently only available on Windows platforms using Swift 6",
I didn't mean remove the `or`. This works for any platform running Swift 6 now
```suggestion
            "markdownDescription": "Use lldb debug adapter packaged with Swift toolchain as your debug adapter. This is currently only available on Windows or platforms using Swift 6",
```

2024-07-11 14:59 UTC, adam-fowler approved these changes
I made one minor change as lldb-dap is available on all platforms using Swift 6
Everything else looks good

2024-07-11 15:18 UTC, merged